name: "Setup Gradle"
description: "Configures Gradle for GitHub actions, caching state and generating a dependency graph"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: gradle/actions/setup-gradle@v4
      with:
        gradle-home-cache-cleanup: true
