[versions]
androidx-activity = "1.6.1"
androidx-lifecycle = "2.5.1"
androidx-paging = "3.1.1"
apollo-graphql = "2.5.13"
arkivanov-decompose = "0.8.0"
cash-paging = "3.1.1-0.1.1"
google-accompanist = "0.27.0"
google-android = "7.3.1"
google-auto = "1.0.1"
google-maps-compose = "2.7.2"
jetbrains-compose = "1.2.1"
jetbrains-kotlin = "1.7.20"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.4.1"
ktor = "2.1.3"
pinterest-ktlint = "0.47.1"
squareup-sqldelight = "1.5.4"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-annotation = "androidx.annotation:annotation:1.5.0"
androidx-compose-foundation = "androidx.compose.foundation:foundation:1.3.1"
androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.0"
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }

apache-batikExt = "org.apache.xmlgraphics:batik-ext:1.14"

apollo-graphql-coroutines-support = { module = "com.apollographql.apollo:apollo-coroutines-support", version.ref = "apollo-graphql" }
apollo-graphql-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo-graphql" }

app-cash-turbine = "app.cash.turbine:turbine:0.12.0"

arkivanov-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "arkivanov-decompose" }
arkivanov-decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "arkivanov-decompose" }

auth-java-jwt = "com.auth0:java-jwt:4.2.1"
auth-jwks-rsa = "com.auth0:jwks-rsa:0.21.2"

cash-paging-common = { module = "app.cash.paging:paging-common", version.ref = "cash.paging" }
cash-paging-runtime = { module = "app.cash.paging:paging-runtime", version.ref = "cash.paging" }

fusesource-jansi = "org.fusesource.jansi:jansi:2.0.1"

google-accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "google-accompanist" }
google-accompanist-placeholderMaterial = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "google-accompanist" }
google-accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "google-accompanist" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "google-accompanist" }

google-android-maps = "com.google.android.gms:play-services-maps:18.1.0"
google-android-material = "com.google.android.material:material:1.7.0"

google-auto-service = { module = "com.google.auto.service:auto-service", version.ref = "google-auto" }
google-auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "google-auto" }

google-cloud-functionsFrameworkApi = "com.google.cloud.functions:functions-framework-api:1.0.4"
google-cloud-javaFunctionInvoker = "com.google.cloud.functions.invoker:java-function-invoker:1.2.0"

google-firebase-admin = "com.google.firebase:firebase-admin:9.1.1"
google-firebase-analytics = "com.google.firebase:firebase-analytics-ktx:21.2.0"
google-firebase-appcheck = "com.google.firebase:firebase-appcheck:16.1.0"
google-firebase-appcheck-debug = "com.google.firebase:firebase-appcheck-debug:16.1.0"
google-firebase-appcheck-playintegrity = "com.google.firebase:firebase-appcheck-playintegrity:16.1.0"
google-firebase-common-ktx = "com.google.firebase:firebase-common-ktx:20.2.0"
google-maps-android-compose = { module = "com.google.maps.android:maps-compose", version.ref = "google-maps-compose" }
google-maps-android-compose-widgets = { module = "com.google.maps.android:maps-compose-widgets", version.ref = "google-maps-compose" }

jakeWharton-mosaic = "com.jakewharton.mosaic:mosaic-runtime:0.2.0"

jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "jetbrains-kotlin" }
jetbrains-kotlinx-cli = "org.jetbrains.kotlinx:kotlinx-cli:0.3.5"
jetbrains-kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-play = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"
jetbrains-kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "kotlinx-serialization" }

jraf-klibnotion = "org.jraf:klibnotion:1.11.0"

ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp3 = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-conditional-headers = { module = "io.ktor:ktor-server-conditional-headers", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }

oolong = "org.oolong-kt:oolong:2.1.1"
qos-logbackClassic = "ch.qos.logback:logback-classic:1.4.4"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.3"

sqldelight-android-driver = { module = "com.squareup.sqldelight:android-driver", version.ref = "squareup-sqldelight" }
sqldelight-coroutines-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "squareup-sqldelight" }
sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "squareup-sqldelight" }
sqldelight-sqlite-driver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "squareup-sqldelight" }

tschuchortdev-kotlin-compile-testing = "com.github.tschuchortdev:kotlin-compile-testing:1.4.9"

[bundles]
androidx-activity = ["androidx-activity-compose", "androidx-activity-ktx"]
androidx-viewmodel = ["androidx-lifecycle-viewmodel-compose", "androidx-lifecycle-viewmodel-ktx"]
arkivanov-decompose = ["arkivanov-decompose", "arkivanov-decompose-extensions"]
google-firebase = ["google-firebase-analytics", "google-firebase-common-ktx"]
google-maps = ["google-android-maps", "google-maps-android-compose", "google-maps-android-compose-widgets"]
jetbrains-kotlin-test = ["jetbrains-kotlin-test", "jetbrains-kotlin-test-annotations", "jetbrains-kotlin-test-common", "jetbrains-kotlin-test-junit", "jetbrains-kotlinx-coroutines-test"]
jetbrains-kotlinx = ["jetbrains-kotlinx-coroutines-core", "jetbrains-kotlinx-datetime", "jetbrains-kotlinx-serialization-core", "jetbrains-kotlinx-serialization-json", "jetbrains-kotlinx-serialization-properties"]
ktor-client = ["ktor-client-content-negotiation", "ktor-client-core", "ktor-client-json", "ktor-client-logging", "ktor-client-okhttp3", "slf4j-simple"]
ktor-serialization = ["ktor-serialization-json", "ktor-serialization-kotlinx"]
ktor-server = ["ktor-client-auth", "ktor-server-auth", "ktor-server-call-logging", "ktor-server-cio", "ktor-server-compression", "ktor-server-conditional-headers", "ktor-server-core", "ktor-server-default-headers"]

[plugins]
android-application = { id = "com.android.application", version.ref = "google-android" }
android-library = { id = "com.android.library", version.ref = "google-android" }
apollo-graphql = { id = "com.apollographql.apollo", version.ref = "apollo-graphql" }
benManes-versions = "com.github.ben-manes.versions:0.44.0"
cash-molecule = { id = "app.cash.molecule", version = "0.4.0" }
catalog-update = "nl.littlerobots.version-catalog-update:0.7.0"
diffplug-spotless = "com.diffplug.spotless:6.11.0"
google-services = "com.google.gms.google-services:4.3.14"
gradle-doctor = "com.osacky.doctor:0.8.1"
jetbrains-dokka = "org.jetbrains.dokka:0.10.0"
johnrengelman-shadow = "com.github.johnrengelman.shadow:7.1.2"
kotlin-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.6.1"
squareup-sqldelight = { id = "com.squareup.sqldelight", version.ref = "squareup-sqldelight" }
