[versions]
androidx-activity = "1.7.1"
androidx-lifecycle = "2.6.1"
apollo-graphql = "2.5.14"
compose-compiler = "1.4.2"
google-accompanist = "0.30.1"
google-android = "8.0.1"
google-auto = "1.0.1"
google-maps-compose = "2.11.4"
jetbrains-compose = "1.4.0"
jetbrains-kotlin = "1.8.20"
kotlinx-coroutines = "1.7.0"
kotlinx-serialization = "1.5.0"
ktor = "2.3.0"
paging-compose = "3.2.0-alpha04-0.2.1"
pinterest-ktlint = "0.47.1"
slack-circuit = "0.8.0"
squareup-sqldelight = "1.5.5"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-annotation = "androidx.annotation:annotation:1.6.0"
androidx-core-ktx = "androidx.core:core-ktx:1.10.1"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"

apollo-graphql-coroutines-support = { module = "com.apollographql.apollo:apollo-coroutines-support", version.ref = "apollo-graphql" }
apollo-graphql-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo-graphql" }

app-cash-turbine = "app.cash.turbine:turbine:0.12.3"
arkivanov-parcelable = "com.arkivanov.essenty:parcelable:1.1.0"

auth-java-jwt = "com.auth0:java-jwt:4.4.0"
auth-jwks-rsa = "com.auth0:jwks-rsa:0.22.0"

fusesource-jansi = "org.fusesource.jansi:jansi:2.4.0"

google-accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "google-accompanist" }
google-accompanist-placeholderMaterial = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "google-accompanist" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "google-accompanist" }

google-android-maps = "com.google.android.gms:play-services-maps:18.1.0"
google-android-material = "com.google.android.material:material:1.9.0"

google-cloud-bom = "com.google.cloud:libraries-bom:26.14.0"
google-cloud-firestore = { module = "com.google.cloud:google-cloud-firestore" }
google-cloud-storage = { module = "com.google.cloud:google-cloud-storage" }
google-cloud-functionsFrameworkApi = "com.google.cloud.functions:functions-framework-api:1.0.4"
google-cloud-javaFunctionInvoker = "com.google.cloud.functions.invoker:java-function-invoker:1.2.1"

google-firebase-admin = "com.google.firebase:firebase-admin:9.1.1"
google-firebase-bom = "com.google.firebase:firebase-bom:32.0.0"
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-appcheck = { module = "com.google.firebase:firebase-appcheck" }
google-firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug" }
google-firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity" }
google-firebase-common-ktx = { module = "com.google.firebase:firebase-common-ktx" }
google-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
google-maps-android-compose = { module = "com.google.maps.android:maps-compose", version.ref = "google-maps-compose" }
google-maps-android-compose-widgets = { module = "com.google.maps.android:maps-compose-widgets", version.ref = "google-maps-compose" }

jakeWharton-mosaic-runtime = "com.jakewharton.mosaic:mosaic-runtime:0.6.0"

jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "jetbrains-kotlin" }
jetbrains-kotlinx-cli = "org.jetbrains.kotlinx:kotlinx-cli:0.3.5"
jetbrains-kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-play = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"
jetbrains-kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "kotlinx-serialization" }

jraf-klibnotion = "org.jraf:klibnotion:1.11.0"

ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp3 = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-conditional-headers = { module = "io.ktor:ktor-server-conditional-headers", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-double-receive = { module = "io.ktor:ktor-server-double-receive", version.ref = "ktor" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
ktor-server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

paging-compose-common = { module = "app.cash.paging:paging-compose-common", version.ref = "paging-compose" }
paging-compose-runtime = { module = "app.cash.paging:paging-runtime-composeui", version.ref = "paging-compose" }

qos-logbackClassic = "ch.qos.logback:logback-classic:1.4.7"

slack-circuit-backstack = { module = "com.slack.circuit:circuit-backstack", version.ref = "slack-circuit" }
slack-circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "slack-circuit" }
slack-circuit-overlay = { module = "com.slack.circuit:circuit-overlay", version.ref = "slack-circuit" }
slack-circuit-retained = { module = "com.slack.circuit:circuit-retained", version.ref = "slack-circuit" }
slack-circuit-test = { module = "com.slack.circuit:circuit-test", version.ref = "slack-circuit" }

slf4j-simple = "org.slf4j:slf4j-simple:2.0.7"

sqldelight-android-driver = { module = "com.squareup.sqldelight:android-driver", version.ref = "squareup-sqldelight" }
sqldelight-coroutines-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "squareup-sqldelight" }
sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "squareup-sqldelight" }
sqldelight-sqlite-driver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "squareup-sqldelight" }

[bundles]
androidx-activity = ["androidx-activity-compose", "androidx-activity-ktx"]
paging-compose = ["paging-compose-common", "paging-compose-runtime"]
google-firebase = ["google-firebase-analytics", "google-firebase-common-ktx"]
google-maps = ["google-android-maps", "google-maps-android-compose", "google-maps-android-compose-widgets"]
jetbrains-kotlin-test = ["jetbrains-kotlin-test", "jetbrains-kotlin-test-annotations", "jetbrains-kotlin-test-common", "jetbrains-kotlin-test-junit", "jetbrains-kotlinx-coroutines-test"]
jetbrains-kotlinx = ["jetbrains-kotlinx-collections-immutable", "jetbrains-kotlinx-coroutines-core", "jetbrains-kotlinx-datetime", "jetbrains-kotlinx-serialization-core", "jetbrains-kotlinx-serialization-json"]
ktor-client = ["ktor-client-content-negotiation", "ktor-client-core", "ktor-client-json", "ktor-client-logging", "ktor-client-okhttp3", "slf4j-simple"]
ktor-serialization = ["ktor-serialization-json", "ktor-serialization-kotlinx"]
ktor-server = ["ktor-server-auth", "ktor-server-call-logging", "ktor-server-cio", "ktor-server-compression", "ktor-server-conditional-headers", "ktor-server-content-negotiation", "ktor-server-core", "ktor-server-default-headers", "ktor-server-request-validation"]
slack-circuit = ["slack-circuit-backstack", "slack-circuit-foundation", "slack-circuit-overlay", "slack-circuit-retained"]

[plugins]
android-application = { id = "com.android.application", version.ref = "google-android" }
android-library = { id = "com.android.library", version.ref = "google-android" }
apollo-graphql = { id = "com.apollographql.apollo", version.ref = "apollo-graphql" }
cash-molecule = { id = "app.cash.molecule", version = "0.9.0" }
diffplug-spotless = "com.diffplug.spotless:6.18.0"
google-cloud-jib = "com.google.cloud.tools.jib:3.3.1"
google-services = "com.google.gms.google-services:4.3.15"
gradle-doctor = "com.osacky.doctor:0.8.1"
jetbrains-dokka = "org.jetbrains.dokka:1.8.10"
jetbrains-terraform = "org.jetbrains.gradle.terraform:1.5.2"
kotlin-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.6.1"
openapi-generator = "org.openapi.generator:6.5.0"
squareup-sqldelight = { id = "com.squareup.sqldelight", version.ref =  "squareup-sqldelight" }
