[versions]
android-compileSdk = "34"
android-minSdk = "24"
androidx-activity = "1.8.2"
apollo-graphql = "2.5.14"
cash-sqldelight = "2.0.1"
coil-kt = "2.5.0"
compose-compiler = "1.5.7"
gitlive-firebase = "1.10.4"
google-accompanist = "0.32.0"
google-android = "8.2.0"
google-auto = "1.0.1"
google-maps-compose = "4.3.0"
google-services = "4.4.0"
jetbrains-compose = "1.5.11"
jetbrains-kotlin = "1.9.22"
kotlin-jvmTarget = "17"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization = "1.6.2"
ktor = "2.3.7"
paging-compose = "3.2.0-alpha05-0.2.3"
pinterest-ktlint = "0.50.0"
slack-circuit = "0.18.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-annotation = "androidx.annotation:annotation:1.7.1"
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version = "1.5.7" }
androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-credentials-auth = "androidx.credentials:credentials-play-services-auth:1.2.0"

apollo-graphql-coroutines-support = { module = "com.apollographql.apollo:apollo-coroutines-support", version.ref = "apollo-graphql" }
apollo-graphql-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo-graphql" }

app-cash-turbine = "app.cash.turbine:turbine:1.0.0"

auth-java-jwt = "com.auth0:java-jwt:4.4.0"
auth-jwks-rsa = "com.auth0:jwks-rsa:0.22.1"

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-kt" }
coil-core = { module = "io.coil-kt:coil", version.ref = "coil-kt" }

essenty-parcelable = "com.arkivanov.essenty:parcelable:1.3.0"
fusesource-jansi = "org.fusesource.jansi:jansi:2.4.1"

gitlive-firebase-app = { module = "dev.gitlive:firebase-app", version.ref = "gitlive-firebase" }

google-accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "google-accompanist" }
google-accompanist-placeholderMaterial = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "google-accompanist" }

google-android-identity = "com.google.android.libraries.identity.googleid:googleid:1.1.0"
google-android-maps = "com.google.android.gms:play-services-maps:18.2.0"
google-android-material = "com.google.android.material:material:1.11.0"

google-cloud-bom = "com.google.cloud:libraries-bom:26.29.0"
google-cloud-firestore = { module = "com.google.cloud:google-cloud-firestore" }
google-cloud-storage = { module = "com.google.cloud:google-cloud-storage" }

google-firebase-admin = "com.google.firebase:firebase-admin:9.2.0"
google-firebase-bom = "com.google.firebase:firebase-bom:32.7.0"
google-firebase-appcheck = { module = "com.google.firebase:firebase-appcheck" }
google-firebase-appcheck-debug = { module = "com.google.firebase:firebase-appcheck-debug" }
google-firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity" }

google-guava-jre = "com.google.guava:guava:33.0.0-jre"

google-maps-android-compose = { module = "com.google.maps.android:maps-compose", version.ref = "google-maps-compose" }
google-maps-android-compose-widgets = { module = "com.google.maps.android:maps-compose-widgets", version.ref = "google-maps-compose" }

jetbrains-compose-compiler = { module = "org.jetbrains.compose.compiler:compiler", version.ref = "compose-compiler" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "jetbrains-kotlin" }
jetbrains-kotlinx-cli = "org.jetbrains.kotlinx:kotlinx-cli:0.3.6"
jetbrains-kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.7"
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-play = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.5.0"
jetbrains-kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "kotlinx-serialization" }

jraf-klibnotion = "org.jraf:klibnotion:1.12.0"

ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-conditional-headers = { module = "io.ktor:ktor-server-conditional-headers", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-double-receive = { module = "io.ktor:ktor-server-double-receive", version.ref = "ktor" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
ktor-server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

material-windowSizeClass = "dev.chrisbanes.material3:material3-window-size-class-multiplatform:0.3.2"
molecule-runtime = "app.cash.molecule:molecule-runtime:1.3.1"
mosaic-runtime = "com.jakewharton.mosaic:mosaic-runtime:0.10.0"

paging-compose-common = { module = "app.cash.paging:paging-compose-common", version.ref = "paging-compose" }
paging-compose-runtime = { module = "app.cash.paging:paging-runtime-composeui", version.ref = "paging-compose" }

qos-logbackClassic = "ch.qos.logback:logback-classic:1.4.14"

slack-circuit-backstack = { module = "com.slack.circuit:circuit-backstack", version.ref = "slack-circuit" }
slack-circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "slack-circuit" }
slack-circuit-overlay = { module = "com.slack.circuit:circuit-overlay", version.ref = "slack-circuit" }
slack-circuit-retained = { module = "com.slack.circuit:circuit-retained", version.ref = "slack-circuit" }
slack-circuit-test = { module = "com.slack.circuit:circuit-test", version.ref = "slack-circuit" }

slf4j-simple = "org.slf4j:slf4j-simple:2.0.10"

sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "cash-sqldelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "cash-sqldelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "cash-sqldelight" }
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "cash-sqldelight" }

squareup-leakcanary = "com.squareup.leakcanary:leakcanary-android:2.12"
squareup-okio = "com.squareup.okio:okio:3.7.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "google-android" }
android-library = { id = "com.android.library", version.ref = "google-android" }
androidx-build-cache = "androidx.build.gradle.gcpbuildcache:1.0.0-beta07"
apollo-graphql = { id = "com.apollographql.apollo", version.ref = "apollo-graphql" }
cash-sqldelight = { id = "app.cash.sqldelight", version.ref = "cash-sqldelight" }
dependency-analysis = "com.autonomousapps.dependency-analysis:1.28.0"
diffplug-spotless = "com.diffplug.spotless:6.23.3"
google-cloud-jib = "com.google.cloud.tools.jib:3.4.0"
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
gradle-doctor = "com.osacky.doctor:0.9.1"
gradle-enterprise = "com.gradle.enterprise:3.16.1"
jetbrains-dokka = "org.jetbrains.dokka:1.9.10"
kotlin-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.7.5"
openapi-generator = "org.openapi.generator:7.2.0"
