[versions]
accompanist = "0.19.0"
android = "7.2.0-alpha03"
anvil = "2.3.5"
apollo = "2.5.9"
benManes = "0.39.0"
compose = "1.1.0-alpha05"
kotlin = "1.5.31"
kotlinX = "1.5.2"
ktlint = "10.2.0"
ktor = "1.6.4"
lifecycle = "2.4.0-rc01"
navigation = "2.4.0-beta02"
sqlDelight = "1.5.1"
versions = "0.39.0"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android" }
androidx-activityKtx = { module = "androidx.activity:activity-ktx", version = "1.3.1" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.3.0-beta01" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-uiTest = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version = "1.7.0-beta02" }
androidx-datastoreCore = { module = "androidx.datastore:datastore-core", version = "1.0.0" }
androidx-fragmentKtx = { module = "androidx.fragment:fragment-ktx", version = "1.4.0-alpha10" }
androidx-lifecycle-viewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.4.0" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-navigation-runtimeKtx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation" }
androidx-navigation-uiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-pagingRuntime = { module = "androidx.paging:paging-runtime", version = "3.1.0-alpha04" }

apache-batikExt = { module = "org.apache.xmlgraphics:batik-ext", version = "1.14" }

apolloGraphQl-apolloCoroutinesSupport = { module = "com.apollographql.apollo:apollo-coroutines-support", version.ref = "apollo" }
apolloGraphQl-apolloGradlePlugin = { module = "com.apollographql.apollo:apollo-gradle-plugin", version.ref = "apollo" }
apolloGraphQl-apolloRuntime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }

dropbox-mobile-store = { module = "com.dropbox.mobile.store:store4", version = "4.0.2-KT15" }

google-android-material = { module = "com.google.android.material:material", version = "1.5.0-alpha04" }
google-accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version = "0.15.0" }
google-accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
google-accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
google-accompanist-insetsUi = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
google-accompanist-placeholderMaterial = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
google-accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

google-cloud-functionsFrameworkApi = { module = "com.google.cloud.functions:functions-framework-api", version = "1.0.4" }
google-cloud-javaFunctionInvoker = { module = "com.google.cloud.functions:java-function-invoker", version = "1.0.3" }

google-firebase-admin = { module = "com.google.firebase:firebase-admin", version = "8.1.0" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics", version = "19.0.2" }
google-firebase-commonKtx = { module = "com.google.firebase:firebase-common-ktx", version = "20.0.0" }

jetbrains-kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
jetbrains-kotlin-testAnnotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
jetbrains-kotlin-testCommon = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
jetbrains-kotlin-testJs = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlin" }
jetbrains-kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
jetbrains-kotlinx-coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinX" }
jetbrains-kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinX" }
jetbrains-kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinX" }
jetbrains-kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.3.0" }
jetbrains-kotlinx-nodejs = { module = "org.jetbrains.kotlinx:kotlinx-nodejs", version = "0.0.7" }
jetbrains-kotlinx-serializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.3.0-RC" }
jetbrains-kotlinx-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.0-RC" }

ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }

pinterest-ktlint = { module = "com.pinterest:ktlint", version = "0.40.0" }

sqlDelight-androidDriver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-coroutinesExtensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-kotlinGradlePlugin = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqlDelight" }
sqlDelight-sqliteDriver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqlDelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
anvil = { id = "com.squareup.anvil", version.ref = "anvil" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }

[bundles]
androidx-navigation = ["androidx-navigation-compose", "androidx-navigation-runtimeKtx", "androidx-navigation-uiKtx"]
apolloGraphQl = ["apolloGraphQl-apolloCoroutinesSupport", "apolloGraphQl-apolloRuntime"]
google-cloud-functions = ["google-cloud-functionsFrameworkApi", "google-cloud-javaFunctionInvoker"]
