[versions]
androidx-activity = "1.4.0"
androidx-lifecycle = "2.4.1"
apollo-graphql = "2.5.11"
arkivanov-decompose = "0.6.0"
cash-molecule = "0.4.0"
google-accompanist = "0.23.1"
google-android = "7.0.4"
google-auto = "1.0.1"
google-maps-compose = "2.5.3"
jetbrains-compose = "1.2.0-alpha01-dev667" # Unstable until 1.2.0-alpha01-dev686 (ClassNotFoundException: CallUtilKt)
jetbrains-compose = "1.2.0-alpha01-dev667"
jetbrains-kotlin = "1.6.10"
kotlinx-coroutines = "1.6.1"
kotlinx-serialization = "1.3.2"
ktor = "2.0.0"
pinterest-ktlint = "0.47.0"
squareup-sqldelight = "1.5.3"

[libraries]
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "google.android" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-annotation = "androidx.annotation:annotation:1.3.0"
androidx-compose-foundation = "androidx.compose.foundation:foundation:1.2.0-alpha07"
androidx-core-ktx = "androidx.core:core-ktx:1.7.0"
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha14"
androidx-paging-runtime = "androidx.paging:paging-runtime:3.1.1"

apache-batikExt = "org.apache.xmlgraphics:batik-ext:1.14"

apollographql-apollo-coroutines-support = { module = "com.apollographql.apollo:apollo-coroutines-support", version.ref = "apollo-graphql" }
apollographql-apollo-gradle-plugin = { module = "com.apollographql.apollo:apollo-gradle-plugin", version.ref = "apollo-graphql" }
apollographql-apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo-graphql" }

arkivanov-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "arkivanov-decompose" }
arkivanov-decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "arkivanov-decompose" }

auth-java-jwt = "com.auth0:java-jwt:3.19.0"
auth-jwks-rsa = "com.auth0:jwks-rsa:0.21.1"

coroutine-dispatcher-core = "com.rickbusarow.dispatch:dispatch-core:1.0.0-beta10"
fusesource-jansi = "org.fusesource.jansi:jansi:2.0.1"

google-auto-service = { module = "com.google.auto.service:auto-service", version.ref = "google-auto" }
google-auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "google-auto" }
google-accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "google-accompanist" }
google-accompanist-placeholderMaterial = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "google-accompanist" }
google-accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "google-accompanist" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "google-accompanist" }

google-android-maps = "com.google.android.gms:play-services-maps:18.0.2"
google-android-material = "com.google.android.material:material:1.5.0"

google-cloud-functionsFrameworkApi = "com.google.cloud.functions:functions-framework-api:1.0.4"
google-cloud-javaFunctionInvoker = "com.google.cloud.functions.invoker:java-function-invoker:1.1.0"

google-firebase-admin = "com.google.firebase:firebase-admin:8.1.0"
google-firebase-appcheck = "com.google.firebase:firebase-appcheck:16.0.0"
google-firebase-analytics = "com.google.firebase:firebase-analytics:20.1.2"
google-firebase-common-ktx = "com.google.firebase:firebase-common-ktx:20.1.0"

google-maps-android-compose = { module = "com.google.maps.android:maps-compose", version.ref = "google-maps-compose" }
google-maps-android-compose-widgets = { module = "com.google.maps.android:maps-compose-widgets", version.ref = "google-maps-compose" }

jakeWharton-mosaic = "com.jakewharton.mosaic:mosaic-runtime:0.1.0"

jetbrains-compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrains-compose" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-serialization-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "jetbrains-kotlin" }
jetbrains-kotlinx-cli = "org.jetbrains.kotlinx:kotlinx-cli:0.3.4"
jetbrains-kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-play = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.2"
jetbrains-kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
jetbrains-kotlinx-serialization-properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "kotlinx-serialization" }

johnRengelman-shadow = "gradle.plugin.com.github.johnrengelman:shadow:7.1.2"
jraf-klibnotion = "org.jraf:klibnotion:1.11.0"

ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp3 = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }

kuuuurt-multiplatform-paging = "io.github.kuuuurt:multiplatform-paging:0.4.7"
molecule-testing = { module = "app.cash.molecule:molecule-testing", version.ref = "cash-molecule" }
oolong = "org.oolong-kt:oolong:2.0.4"
qos-logbackClassic = "ch.qos.logback:logback-classic:1.2.11"
requery-sqlite-android = "com.github.requery:sqlite-android:3.36.0"
slf4j-simple = "org.slf4j:slf4j-simple:1.7.21"

sqldelight-android-driver = { module = "com.squareup.sqldelight:android-driver", version.ref = "squareup-sqldelight" }
sqldelight-coroutines-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "squareup-sqldelight" }
sqldelight-kotlin-gradle-plugin = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "squareup-sqldelight" }
sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "squareup-sqldelight" }
sqldelight-sqlite-driver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "squareup-sqldelight" }

tschuchortdev-kotlin-compile-testing = "com.github.tschuchortdev:kotlin-compile-testing:1.4.9"

[bundles]
androidx-activity = ["androidx-activity-compose", "androidx-activity-ktx"]
androidx-paging = ["androidx-paging-compose", "androidx-paging-runtime"]
androidx-viewmodel = ["androidx-lifecycle-viewmodel-compose", "androidx-lifecycle-viewmodel-ktx"]
arkivanov-decompose = ["arkivanov-decompose", "arkivanov-decompose-extensions"]
google-firebase = ["google-firebase-analytics", "google-firebase-common-ktx"]
google-maps = ["google-android-maps", "google-maps-android-compose", "google-maps-android-compose-widgets"]
jetbrains-kotlinx = ["jetbrains-kotlinx-coroutines-core", "jetbrains-kotlinx-datetime", "jetbrains-kotlinx-serialization-core", "jetbrains-kotlinx-serialization-json", "jetbrains-kotlinx-serialization-properties"]
jetbrains-kotlin-test = ["jetbrains-kotlin-test", "jetbrains-kotlin-test-annotations", "jetbrains-kotlin-test-common", "jetbrains-kotlin-test-junit", "jetbrains-kotlinx-coroutines-test"]
ktor-client = ["ktor-client-okhttp3", "ktor-client-content-negotiation", "ktor-client-core", "ktor-client-json", "ktor-client-logging", "ktor-serialization-json", "ktor-serialization-kotlinx", "slf4j-simple"]
ktor-server = ["ktor-client-auth", "ktor-serialization-json", "ktor-serialization-kotlinx", "ktor-server-auth", "ktor-server-call-logging", "ktor-server-cio", "ktor-server-core", "ktor-server-html-builder"]

[plugins]
android-application = { id = "com.android.application", version.ref = "google.android" }
android-library = { id = "com.android.library", version.ref = "google.android" }
cash-molecule = { id = "app.cash.molecule", version.ref = "cash-molecule" }
diffplug-spotless = "com.diffplug.spotless:6.9.1"
gradle-doctor = "com.osacky.doctor:0.8.0"
gradle-publish = "com.gradle.plugin-publish:0.11.0"
jetbrains-dokka = "org.jetbrains.dokka:0.10.0"
jetbrains-kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version = "0.5.0" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "squareup-sqldelight" }
version-catalog-update = "nl.littlerobots.version-catalog-update:0.3.1"
versions = "com.github.ben-manes.versions:0.42.0"
