name: "Create Comment"
description: "Comments a pull request with the provided message"

inputs:
  message:
    description: "Message that should be printed in the pull request"
    required: true

  tag:
    description: "A tag that will be used to identify a comment in case of replacement"
    required: false

  token:
    description: "The GitHub token to use for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - uses: thollander/actions-comment-pull-request@v3
      with:
        comment_tag: ${{ inputs.tag }}
        message: ${{ inputs.message }}
        mode: recreate
