name: Update Screenshots

inputs:
  service_account_token:
    description: Your 1Password service account token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: 1password/load-secrets-action/configure@v2
      with:
        service-account-token: ${{ inputs.service_account_token }}

    - id: op-secrets
      uses: 1password/load-secrets-action@v2
      with:
        export-env: false
      env:
        GOOGLE_SERVICES: op://development/google services/playground release/base64

    - run: echo $GOOGLE_SERVICES | base64 --decode > conferences-app/google-services.json
      shell: bash
      env:
        GOOGLE_SERVICES: ${{ steps.op-secrets.outputs.GOOGLE_SERVICES }}

    - uses: ./.github/actions/setup-gradle

    - run: ./gradlew updateScreenshotTest --console=plain
      shell: bash
      env:
        ANDROID_API_KEY:
        BROWSER_API_KEY:
        GITHUB_TOKEN:
        SERVER_CLIENT_ID:

    - run: |
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
      shell: bash

    - id: snapshots
      run: |
        PR_NUMBER=${GITHUB_REF#refs/pull/}
        PR_NUMBER=${PR_NUMBER/\/merge/}
        BRANCH_NAME="snapshots/pr-$PR_NUMBER"
        echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        
        git checkout -b $BRANCH_NAME
        git commit -am "Update screenshots"
        git push -u origin $BRANCH_NAME
      shell: bash

    - uses: thollander/actions-comment-pull-request@v3
      with:
        message: "Screenshot tests failed.\\n\\n[See differences](https://github.com/${{ github.repository }}/compare/${{ github.head_ref }}...${{ steps.snapshots.outputs.branch-name }})"
        comment-tag: build-scan-url
        mode: recreate
