name: Update Screenshots

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-gradle

    - run: ./gradlew updateScreenshotTest --console=plain
      shell: bash
      env:
        ANDROID_API_KEY:
        BROWSER_API_KEY:
        GITHUB_TOKEN:
        SERVER_CLIENT_ID:

    - run: |
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
      shell: bash

    - id: snapshots
      run: |
        PR_NUMBER=${${GITHUB_REF#refs/pull/}/\/merge/}
        BRANCH_NAME="snapshots/pr-$PR_NUMBER"
        echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        
        git checkout --track "origin/$PR_BRANCH"
        git checkout -b "$NEW_BRANCH_NAME"
        git commit -am "Update screenshots"
        git push origin
      shell: bash

    - uses: thollander/actions-comment-pull-request@v3
      with:
        message: "Screenshot tests failed.\\n\\n[See differences](https://github.com/${{ github.repository }}/compare/${{ github.head_ref }}...${{ steps.snapshots.outputs.branch-name }})"
        comment-tag: build-scan-url
        mode: recreate
