name: Android Release

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      log_level:
        type: choice
        description: Log Level
        required: false
        default: info
        options:
          - error
          - quiet
          - warning
          - lifecycle
          - info
          - debug

      monitor_permissions:
        type: boolean
        description: Monitor Permissions
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Assemble Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.logging.level=${{ github.event.inputs.log_level || 'info' }}"

    permissions:
      pull-requests: 'write'
      id-token: 'write'

    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        if: ${{ github.event.inputs.monitor_permissions == 'true' }}

      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-cloud
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          setup_gcloud: false

      - uses: ./.github/actions/setup-gradle

      - uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - id: op-secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          GOOGLE_SERVICES: op://development/google services/playground release/base64
          KEYSTORE_BASE64: op://development/playground keystore/keystore base64
          KEYSTORE_PASSWORD: op://development/playground keystore/keystore password
          KEY_ALIAS: op://development/playground keystore/key alias
          KEY_PASSWORD: op://development/playground keystore/key password

      - env:
          GOOGLE_SERVICES: ${{ steps.op-secrets.outputs.GOOGLE_SERVICES }}
          KEYSTORE_BASE64: ${{ steps.op-secrets.outputs.KEYSTORE_BASE64 }}
        run: |
          echo $GOOGLE_SERVICES | base64 --decode > app-launcher/android/google-services.json
          echo $GOOGLE_SERVICES | base64 --decode > conferences-app/google-services.json
          echo $KEYSTORE_BASE64 | base64 --decode > keystore.jks

      - id: gradle
        env:
          ANDROID_API_KEY: ${{ secrets.ANDROID_API_KEY }}
          BROWSER_API_KEY: ${{ secrets.BROWSER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEY_STORE_FILE: keystore.jks
          KEY_STORE_PASSWORD: ${{ steps.op-secrets.outputs.KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ steps.op-secrets.outputs.KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ steps.op-secrets.outputs.KEY_PASSWORD }}
          SERVER_CLIENT_ID: ${{ secrets.SERVER_CLIENT_ID }}
        run: ./gradlew assembleRelease --console=plain

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: apk-release
          path: "**/*-release.apk"
