name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Google Cloud Auth
      id: google_cloud_auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY }}
        service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Decrypt Google Services
      env:
        GOOGLE_SERVICES_PASSPHRASE: ${{ secrets.google_services_passphrase }}
      run: find . -type f -name "google-services.aes" -exec sh -c 'openssl aes-256-cbc -md sha256 -d -in "$0" -out "${0%.aes*}.json" -k "${GOOGLE_SERVICES_PASSPHRASE}"' {} \;

    - name: Run build with Gradle Wrapper
      run: ./gradlew build
