on:
  workflow_call:
    inputs:
      body:
        required: true
        type: string
    secrets:
      token:
        default: ${{ secrets.GITHUB_TOKEN }}
        required: true

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.token }}
        script: |
          const comments = require('./.github/workflows/scripts/comments.js');
          await comments.create(context, github, ${{ github.event.inputs.body }});
