name: Configure Google Cloud

on:
  push:
    branches:
      - main

  pull_request:
    types: [ labeled, opened, reopened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'Google Cloud')
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Google Cloud Auth
        id: google_cloud_auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          token_format: access_token

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker Auth
        uses: docker/login-action@v2
        with:
          username: oauth2accesstoken
          password: ${{ steps.google_cloud_auth.outputs.access_token }}
          registry: europe-west1-docker.pkg.dev

      - name: Create Terraform Plan
        uses: gradle/gradle-build-action@v2
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        if: github.event_name == 'pull_request'
        with:
          arguments: |
            ./gradlew google-cloud:terraformPlan
              --no-configuration-cache
              --console=plain
              --info

      - name: Containerize Cloud Run
        uses: gradle/gradle-build-action@v2
        env:
          GOOGLE_PROJECT_API_KEY: ${{ secrets.google_project_api_key }}
          GOOGLE_SERVICE_ACCOUNT_ID: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          MOBILE_SDK_APP_ID: ${{ secrets.mobile_sdk_app_id }}
          PLAYGROUND_API_KEY: ${{ secrets.PLAYGROUND_API_KEY }}
        if: github.ref == 'refs/heads/main'
        with:
          arguments: |
            cloud-run:jib
              --image=europe-west1-docker.pkg.dev/${{ steps.google_cloud_auth.outputs.project_id }}/cloud-run-source-deploy/playground.ashdavies.dev \
              --no-configuration-cache
              --console=plain
              --info

      - name: Apply Terraform Config
        uses: gradle/gradle-build-action@v2
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        if: github.ref == 'refs/heads/main'
        with:
          arguments: |
            ./gradlew google-cloud:terraformApply
              --no-configuration-cache
              --console=plain
              -Ptf.apply
              --info
