name: Run Integration Tests

on:
  schedule:
    - cron: "0 8 * * *"

  workflow_dispatch:
    inputs:
      log_level:
        type: choice
        description: Log Level
        required: false
        default: info
        options:
          - error
          - quiet
          - warning
          - lifecycle
          - info
          - debug

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.logging.level=${{ github.event.inputs.log_level || 'info' }}"

    permissions:
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - id: setup-cloud
        uses: ./.github/actions/setup-cloud
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          setup_gcloud: false

      - uses: ./.github/actions/setup-gradle

      - name: Run Gradle Tasks
        id: gradle_build
        env:
          FIREBASE_ANDROID_APP_ID: ${{ secrets.firebase_android_app_id }}
          GOOGLE_SERVICE_ACCOUNT_ID: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          INTEGRATION_API_KEY: ${{ secrets.integration_api_key }}
        run: ./gradlew cloud-run:integrationTest --console=plain

      - name: Produce Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/build/test-results/test/TEST-*.xml"
        if: ${{ always() }}
