name: Pre Merge Checks
on: [ pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Pre Merge Checks
    runs-on: ubuntu-latest

    permissions:
      pull-requests: 'write'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Decrypt Google Services
        env:
          GOOGLE_SERVICES_PASSPHRASE: ${{ secrets.google_services_passphrase }}
        run: find . -type f -name "google-services.aes" -exec sh -c 'openssl aes-256-cbc -md sha256 -d -in "$0" -out "${0%.aes*}.json" -k "${GOOGLE_SERVICES_PASSPHRASE}"' {} \;

      - id: setup-cloud
        uses: ./.github/actions/setup-cloud
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          setup_gcloud: false

      - uses: ./.github/actions/setup-gradle

      - id: gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_PROJECT_API_KEY: ${{ secrets.google_project_api_key }}
          GOOGLE_SERVICE_ACCOUNT_ID: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          PLAYGROUND_API_KEY: ${{ secrets.PLAYGROUND_API_KEY }}
          SERVER_CLIENT_ID: ${{ secrets.SERVER_CLIENT_ID }}
        run: ./gradlew build --console=plain

      - name: Gradle Scan Link
        uses: ./.github/actions/pull-comment
        if: ${{ steps.gradle.outputs.build-scan-url }}
        with:
          message: "Build scan published to ${{ steps.gradle.outputs.build-scan-url }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: build-scan-url

      - uses: test-summary/action@v2
        with:
          paths: "**/build/test-results/test/TEST-*.xml"
