name: Pre Merge Checks

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  PLAYGROUND_API_KEY: ${{ secrets.PLAYGROUND_API_KEY }}

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper

#      - name: Encrypt Google Services config file
#        run:  openssl aes-256-cbc -md sha256 -salt -in android/google-services.json -out android/google-services.aes -k ${{ secrets.GOOGLE_SERVICES_PASSPHRASE }}

      - name: Decrypt Google Services config file
        run: openssl aes-256-cbc -md sha256 -d -in android/google-services.aes -out android/google-services.json -k ${{ secrets.GOOGLE_SERVICES_PASSPHRASE }}

      - name: Run Gradle tasks
        run: ./gradlew build check

      - name: Display dependency updates
        run: ./gradlew dependencyUpdates

      - name: Stop Gradle
        run: ./gradlew --stop
