name: Pre Merge Checks

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

env:
  APP_CHECK_KEY: ${{ secrets.APP_CHECK_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  PLAYGROUND_API_KEY: ${{ secrets.PLAYGROUND_API_KEY }}
  SERVICE_ACCOUNT_ID: ${{ secrets.SERVICE_ACCOUNT_ID }}

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Gradle caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper

#      - name: Generate encryption passphrase
#      - run: openssl rand -base64 32

#      - name: Encrypt Google Services config file
#        run: find . -type f -name "google-services.json" -exec sh -c 'openssl aes-256-cbc -md sha256 -salt -in "$0" -out "${0%.json*}.aes" -k "${GOOGLE_SERVICES_PASSPHRASE}"' {} \;

      - name: Decrypt Google Services config file
        run: find . -type f -name "google-services.aes" -exec sh -c 'openssl aes-256-cbc -md sha256 -d -in "$0" -out "${0%.aes*}.json" -k "${GOOGLE_SERVICES_PASSPHRASE}"' {} \;

      - name: Run Gradle tasks
        run: ./gradlew build check

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: "**/build/reports/tests/test/*.html"
          if-no-files-found: error
        if: failure()

      - name: Test Artifact
        uses: test-summary/action@v1.0
        with:
           name: Package
           paths: "**/build/reports/tests/*.html"

      - name: Test Summary
        uses: test-summary/action@v1.0
        with:
          paths: "**/build/test-results/test/TEST-*.xml"

      - name: Upload Test Summary
        uses: actions/upload-artifact@v3
        with:
          name: test-summary
          path: test-summary.md
          if-no-files-found: error
        if: always()

      - name: Display dependency updates
        run: ./gradlew dependencyUpdates

      - name: Stop Gradle
        run: ./gradlew --stop
