name: Pre Merge Checks

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  PLAYGROUND_API_KEY: ${{ secrets.PLAYGROUND_API_KEY }}

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper

#      - name: Generate encryption passphrase
#      - run: openssl rand -base64 32

#      - name: Encrypt Google Services config file
#        run: find . -type f -name "google-services.json" -exec sh -c 'openssl aes-256-cbc -md sha256 -salt -in "$0" -out "${0%.json*}.aes" -k "${GOOGLE_SERVICES_PASSPHRASE}"' {} \;

      - name: Decrypt Google Services config file
        run: find . -type f -name "google-services.aes" -exec sh -c 'openssl aes-256-cbc -md sha256 -d -in "$0" -out "${0%.aes*}.json" -k "${GOOGLE_SERVICES_PASSPHRASE}"' {} \;

      - name: Run Gradle tasks
        run: ./gradlew build check

      - name: TestForest Dashboard
        uses: test-summary/action@v1.0

      - name: Display dependency updates
        run: ./gradlew dependencyUpdates

      - name: Stop Gradle
        run: ./gradlew --stop
