name: Renovate

on:
#  schedule:
#    - cron: "0 8 * * *"

  pull_request:
    branches:
      - '*'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.82.0
        with:
          configurationFile: .github/renovate.json
          token: '${{ steps.get_token.outputs.token }}'
        env:
          LOG_LEVEL: 'debug'
