name: Renovate

on:
  pull_request:
    branches:
      - '*'

  schedule:
    - cron: "0 8 * * *"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'INFO'
        type: choice
        options:
          - DEBUG
          - INFO
          - WARN
          - ERROR
          - FATAL

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Verify
        uses: actions/github-script@v6
        with:
#         github-token: ${{ steps.get_token.outputs.token }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commits = require('./.github/workflows/scripts/commits.js');
            const pulls = require('./.github/workflows/scripts/pulls.js');

            const open = await pulls.findAll(context, github, (it) => {
              it.head.ref.startsWith("renovate")
            })

            for (const pull of open) {
              const unverified = await commits.findAll(context, github, pull.number, (it) => {
                it.commit.verification.verified == false && it.commit.verification.reason == "unsigned"
              })

              for (const commit of unverified) {
                const payload = {
                  parents: commit.parents.map(it => it.sha),
                  message: commit.commit.message,
                  author: commit.commit.author,
                  tree: commit.commit.tree.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                }

                console.log("=== Bot Commit ===")
                console.log(commit)

                console.log("=== Commit Payload ===")
                console.log(payload)

                await github.rest.git.createCommit(payload)
              }
            }

#     - name: Self-hosted Renovate
#       uses: renovatebot/github-action@v35.2.0
#       env:
#         LOG_LEVEL: ${{ inputs.logLevel || 'INFO' }}
#       with:
#         configurationFile: .github/renovate.json
#         token: '${{ steps.get_token.outputs.token }}'
