name: Self-Hosted Renovate

on:
  schedule:
    - cron: "0 8 * * *"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'INFO'
        type: choice
        options:
          - DEBUG
          - INFO
          - WARN
          - ERROR
          - FATAL

jobs:
  renovate:
    name: Self-Hosted
    runs-on: ubuntu-latest
    steps:
#     - name: Permissions Monitor
#       uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v35.2.0
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'INFO' }}
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.generate_token.outputs.token }}
