name: Renovate

on:
  pull_request:
    branches:
      - '*'

  schedule:
    - cron: "0 8 * * *"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'INFO'
        type: choice
        options:
          - DEBUG
          - INFO
          - WARN
          - ERROR
          - FATAL

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Verify
        uses: actions/github-script@v6
        with:
#         github-token: ${{ steps.get_token.outputs.token }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            })

            for (const pull of pulls) {
              console.log("=== Open Pull Request ===")
              console.log(pull)
            }

#     - name: Self-hosted Renovate
#       uses: renovatebot/github-action@v35.2.0
#       env:
#         LOG_LEVEL: ${{ inputs.logLevel || 'INFO' }}
#       with:
#         configurationFile: .github/renovate.json
#         token: '${{ steps.get_token.outputs.token }}'
