name: Renovate

on:
  schedule:
    - cron: "0 8 * * *"

  pull_request:
    branches:
      - '*'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Renovate
        uses: renovatebot/github-action@v34.152.3
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
