name: Configure Terraform

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      log_level:
        type: choice
        description: Log Level
        required: false
        default: info
        options:
          - error
          - quiet
          - warning
          - lifecycle
          - info
          - debug

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Configure Google Cloud
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.logging.level=${{ github.event.inputs.log_level || 'info' }}"

    permissions:
      pull-requests: 'write'
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: setup-cloud
        uses: ./.github/actions/setup-cloud
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          token_format: access_token

      - uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.setup-cloud.outputs.access_token }}
          registry: europe-west1-docker.pkg.dev

      - uses: ./.github/actions/setup-gradle
        if: ${{ github.ref == 'refs/heads/main' }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        env:
          FIREBASE_ANDROID_APP_ID: ${{ secrets.firebase_android_app_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_PROJECT_API_KEY: ${{ secrets.google_project_api_key }}
          GOOGLE_SERVICE_ACCOUNT_ID: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          PLAYGROUND_API_KEY: ${{ secrets.PLAYGROUND_API_KEY }}
        run: >
            ./gradlew cloud-run:jib
            --image=europe-west1-docker.pkg.dev/${{ steps.google_cloud_auth.outputs.project_id }}/cloud-run-source-deploy/playground.ashdavies.dev
            --no-configuration-cache
            --console=plain

      - id: token
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - id: init
        run: terraform -chdir=terraform init

      - id: plan
        env:
          TF_VAR_gh_token: ${{ steps.token.outputs.token }}
          TF_LOG: ${{ inputs.debug && 'DEBUG' || 'ERROR' }}
          TF_INPUT: false
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          terraform -chdir=terraform plan >/dev/null -lock-timeout=5m -out=.terraform/terraform.tfplan
          terraform -chdir=terraform show .terraform/terraform.tfplan -no-color

      - uses: ./.github/actions/pull-comment
        if: ${{ github.event_name == 'pull_request' }}
        with:
          message: "```${{ steps.plan.outputs.stdout }}```"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: terraform-plan

      - id: apply
        env:
          TF_LOG: ${{ inputs.debug && 'DEBUG' || 'ERROR' }}
          TF_VAR_gh_token: ${{ steps.token.outputs.token }}
          TF_INPUT: false
        if: ${{ github.ref == 'refs/heads/main' }}
        run: terraform -chdir=terraform apply -auto-approve -lock-timeout=5m
