name: Configure Terraform

on:
  push:
    branches:
      - main

  pull_request:
    types: [ labeled, opened, reopened, synchronize ]
    branches:
      - '*'

  workflow_dispatch:
    inputs:
      log_level:
        type: choice
        description: Log Level
        required: false
        default: info
        options:
          - error
          - quiet
          - warning
          - lifecycle
          - info
          - debug

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Configure Google Cloud
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.logging.level=${{ github.event.inputs.log_level || 'info' }}"

    permissions:
      pull-requests: 'write'
      id-token: write

    steps:
#     - name: Permissions Monitor
#       uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - id: token
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - id: google_cloud_auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          token_format: access_token

      - uses: google-github-actions/setup-gcloud@v2

      - uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.google_cloud_auth.outputs.access_token }}
          registry: europe-west1-docker.pkg.dev

      - uses: gradle/gradle-build-action@v2
        env:
          FIREBASE_ANDROID_APP_ID: ${{ secrets.firebase_android_app_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_PROJECT_API_KEY: ${{ secrets.google_project_api_key }}
          GOOGLE_SERVICE_ACCOUNT_ID: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          PLAYGROUND_API_KEY: ${{ secrets.PLAYGROUND_API_KEY }}
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          gradle-home-cache-cleanup: true
          arguments: >
            cloud-run:jib
              --image=europe-west1-docker.pkg.dev/${{ steps.google_cloud_auth.outputs.project_id }}/cloud-run-source-deploy/playground.ashdavies.dev
              ${{ contains(github.event.pull_request.labels.*.name, 'Dry Run') && '--dry-run' || '' }}
              --no-configuration-cache
              --console=plain

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5

      - id: init
        run: terraform -chdir=terraform init

      - id: plan
        env:
          TF_INPUT: 0
          TF_LOG: ${{ inputs.debug && 'DEBUG' || 'ERROR' }}
          TF_VAR_gh_token: ${{ steps.token.outputs.token }}
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          terraform -chdir=terraform plan >/dev/null -lock-timeout=5m -out=.terraform/terraform.tfplan
          terraform -chdir=terraform show .terraform/terraform.tfplan -no-color

      - uses: .github/actions/create-comment
        if: ${{ github.event_name == 'pull_request' }}
        with:
          message: "```${{ steps.plan.outputs.stdout }}```"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: terraform-plan

      - id: apply
        env:
          TF_VAR_gh_token: ${{ steps.token.outputs.token }}
          TF_LOG: ${{ inputs.debug && 'DEBUG' || 'ERROR' }}
          TF_INPUT: 0
        if: ${{ github.ref == 'refs/heads/main' }}
        run: terraform -chdir=terraform apply -auto-approve -lock-timeout=5m
